---
title: "seascapes"
output: html_document
---

```{r mat to grd, eval=F}
library(tidyverse)
library(R.matlab)
library(raster)
library(stringr)
library(lubridate)

dir_wd = 'satellite'

if (basename(getwd()) != dir_wd) setwd('satellite')

dir_root = switch(
  Sys.info()[['sysname']],
  'Darwin'  = '/Volumes/Best HD/mbon_data_big', # BB's Mac
  'Windows' = 'P:',                                          # constance.bren.ucsb.edu
  'Linux'   = '/mbon/data_big')                 # mbon.marine.usf.edu

dir_mat = file.path(dir_root, 'satellite/seascapes/gl')
grd   = file.path(dir_mat, 'GLOBE14_I90VAR3_9k.grd')
grd_l = file.path(dir_mat, 'GLOBE14_I90VAR3_9k_leaflet.grd')

mats = tibble(
  mat = list.files(dir_mat, '\\.mat$')) %>%
  mutate(
    yj   = str_replace(mat, 'GLOBE14_I90VAR3_9k_(.*).mat', '\\1'),
    lyr  = sprintf('lyr%s', yj),
    date = as.Date(sprintf('%s-01-01', str_sub(yj,1,4))) + days(as.integer(str_sub(yj,5,8))-1))

L = list()
for (i in 1:nrow(mats)){ # i = 2
  mat = file.path(dir_mat, mats$mat[i])
  lyr  = mats$lyr[i]
  
  m = readMat(mat)
  r = raster(m$CLASS)
  L[[lyr]] = r
}

s = stack(L) %>% 
  flip('y') %>% 
  setExtent(extent(-180, 180, -90, 90))
crs(s) = leaflet:::epsg4326
names(s) = mats$lyr

#names(s)
#plot(raster(s, lyr))
writeRaster(s, grd, overwrite=T)

# raster stack for leaflet
s = stack(grd)
s_l = leaflet::projectRasterForLeaflet(s)

# rename layers to dates, using mid-month day of 15th
yjs   = str_replace(names(s), 'lyr', '')
dates = as.Date(sprintf('%s-01-15', str_sub(yjs,1,4))) + days(as.integer(str_sub(yjs,5,8))-1)
names(s_l) = format(dates, 'ymd_%Y.%m.%d')

writeRaster(s_l, grd_l, overwrite=T)
```


```{r scrap}
r <- raster(nc=5, nr=5)
r[] <- runif(ncell(r)) * 2
plot(r)
s <- setValues(r, runif(ncell(r)) * 3)
plot(s)
crosstab(r,s)


rs <- r/s
r[1:5] <- NA
s[20:25] <- NA
x <- stack(r, s, rs)
crosstab(x, useNA=TRUE, long=TRUE)


r <- raster(ncol=36, nrow=18)
r[] <- 1:ncell(r)

cds1 <- rbind(c(-180,-20), c(-160,5), c(-60, 0), c(-160,-60), c(-180,-20))
cds2 <- rbind(c(80,0), c(100,60), c(120,0), c(120,-55), c(80,0))
polys <- spPolygons(cds1, cds2)

a = area(r)

plot(r)
plot(a)
s = stack(r, a)

plot(polys, add=TRUE)
v <- raster::extract(r, polys)
w <- raster::extract(s, polys)
w <- raster::extract(s, polys, df=T)
w
# mean for each polygon
unlist(lapply(v, function(x) if (!is.null(x)) mean(x, na.rm=TRUE) else NA ))

v <- raster::extract(r, polys, cellnumbers=TRUE)
```


```{r extract eez}
library(sf)
s = stack(grd)
s = stack(s, area(s[[1]]))
names(s)[nlayers(s)] = 'area_km2'

eez_s005_shp    = '/mbon/data_big/technical/boundaries/eez_derived/eez_s005.shp'
eez_sp = read_sf(eez_s005_shp) %>% as('Spatial')
eez_sp$GeoName[duplicated(eez_sp$GeoName)]
plot(eez_sp['GeoName'])

system.time({
  s_e = raster::extract(s, eez_sp, na.rm=T, df=T)
}) # 2.7 hrs

write_rds(s_e, '/mbon/data_big/satellite/seascapes/gl/gl-seascape-eez-extract.Rdata')
s_e = read_rds('/mbon/data_big/satellite/seascapes/gl/gl-seascape-eez-extract.Rdata')

select = dplyr::select
d = eez_sp@data %>%
  select(MRGID) %>%
  mutate(
    ID = row_number()) %>%
  left_join(
    s_e,
    by='ID') %>%
  gather(lyr, category, -MRGID, -ID, -area_km2, na.rm=T) %>%
  group_by(MRGID, lyr, category) %>%
  summarize(
    area_km2 = sum(area_km2)) %>%
  mutate(
    yj   = str_replace(lyr, 'lyr', ''),
    date = as.Date(sprintf('%s-01-01', str_sub(yj,1,4))) + days(as.integer(str_sub(yj,5,8))-1)) %>%
  ungroup() %>%
  mutate(category = as.integer(category)) %>%
  arrange(date, MRGID, category) %>%
  select(date, MRGID, category, area_km2)

#list.files('/mbon/data_big/satellite/seascapes/gl/')
#d0_csv = sprintf('%s_eez-area-km2.csv', tools::file_path_sans_ext(grd))
d_csv = sprintf('%s_leaflet_eez-area-km2.csv', tools::file_path_sans_ext(grd))
#file.rename(d_0csv, d_csv)
write_csv(d, d_csv)

d = read_csv(d_csv)
d = eez_sp@data %>%
  left_join(d, by='MRGID')

#View(d) # names(d)
library(xts)
x = d %>%
  filter(GeoName=="Spanish Exclusive Economic Zone") %>%
  select(date, category, area_km2) %>%
  mutate(
    area_km2 = round(area_km2, 1)) %>%
  spread(category, area_km2, fill=0)
x = xts(select(x, -date), order.by=x$date)

library(dygraphs) # install.packages("dygraphs")

#the axis label is passed as a date, this function outputs only the month of the date
getMonth <- 'function(d){
  var monthNames = ["Jan", "Feb", "Mar", "Apr", "May", "Jun","Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];
  return monthNames[d.getMonth()]; }'

#the x values are passed as milliseconds, turn them into a date and extract month and day
getMonthDay <- 'function(d) {
  var monthNames = ["Jan", "Feb", "Mar", "Apr", "May", "Jun","Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];
  date = new Date(d);
  //return monthNames[date.getMonth()] + " " +date.getUTCDate(); }
  return monthNames[date.getMonth()]; }'

lungDeaths <- cbind(mdeaths, fdeaths)
dygraph(lungDeaths) %>%
  dySeries("mdeaths", label = "Male") %>%
  dySeries("fdeaths", label = "Female") %>%
  dyOptions(stackedGraph = TRUE) %>%
  dyRangeSelector(height = 20)


dygraph(x, main = "Seascapes") %>%
  # dySeries(c('lwr_sd', 'mean', 'upr_sd'), label = "Chl a") %>%
  # dySeries("mdeaths", label = "Male") %>%
  # dySeries("fdeaths", label = "Female") %>%
  dyOptions(stackedGraph = TRUE) #%>%

  dyAxis("x",valueFormatter=JS(getMonthDay), axisLabelFormatter=JS(getMonth))
```

```{r streamgraph}
library(streamgraph)
select = dplyr::select
x = d %>%
  filter(GeoName=="Spanish Exclusive Economic Zone") %>%
  select(date, category, area_km2) %>%
  arrange(category, date) %>%
  mutate(
    area_km2 = round(area_km2, 1),
    category = factor(as.character(category), as.character(1:14), ordered=T)) %>%
  as_tibble()
x
x$category

pal = colorNumeric('Spectral', 1:14, na.color='transparent')

streamgraph(x, category, area_km2, date) %>%
  sg_legend(show=T, label="Category:") %>%
  sg_fill_manual(pal(1:14))
  #sg_colors('Spectral')
  
```



```{r streamgraph babynames}
library(babynames)   # install.packages('babynames')
library(streamgraph) # devtools::install_github('hrbrmstr/streamgraph')

b = babynames %>%
  filter(grepl("^Kr", name)) %>%
  group_by(year, name) %>%
  tally(wt=n) %>%
  arrange(year, name)
View(b)
streamgraph(b, "name", "nn", "year")
```


```{r prep chl}
chl_dir = '/mbon/data_big/satellite/chlor_a/clim_27km'
chl_nc = list.files(chl_dir, '.*\\.nc$', full.names=T)
  
for (nc_path in chl_nc){ # nc_path = chl_nc[1]
  
  grd   = sprintf('%s.grd', tools::file_path_sans_ext(nc_path))
  grd_l = sprintf('%s_leaflet.grd', tools::file_path_sans_ext(nc_path))
  
  if (!file.exists(grd)){
  
    # fetch nc
    nc = nc_open(nc_path)
    lon = ncvar_get(nc, 'longitude')[,1]
    lat = ncvar_get(nc, 'latitude')[1,]
    vars = str_subset(names(nc$var), '.*_chlor_a_clim$')
    
    # extract rasters
    s = stack(raster(nc_path, varname=vars[1]))
    for (v in vars[-1]){
      s = stack(s, raster(nc_path, varname=v))
    }
    names(s) = vars
    
    # realign spatial
    s = flip(s, direction='y')
    s <- setExtent(s, extent(min(lon), max(lon), min(lat), max(lat)))
    crs(s) <- leaflet:::epsg4326
    
    # write out
    writeRaster(s, grd, overwrite=T)
  }
  
  # rasters for leaflet
  #if (!file.exists(grd_l)){
  if (T){
  #if (nc_path != '/mbon/data_big/satellite/chlor_a/clim_27km/A20032007_chlor_a_CLIM_MO_GLOB_27km.nc'){
    s = stack(grd)
    s_l = leaflet::projectRasterForLeaflet(s)

    # rename layers to dates, using mid-month day of 15th
    yr = 2005
    # TODO: vary yr with input grd based on filename
    dates = as.Date(plyr::mapvalues(
      names(s),
      sprintf('%s_chlor_a_clim', month.name),
      sprintf('%s-%02d-15', yr, 1:12)))
    names(s_l) = format(dates, 'ymd_%Y.%m.%d')

    writeRaster(s_l, grd_l, overwrite=T)
  }
}
```


## Maps

The legend title describes the value [CLASS|P].[OCI|sw] and the layers are labeled according to month and day (MMDD) of the start.

```{r leaflet, warning=F, message=F}
library(tidyverse)
library(raster)
library(leaflet)

if (basename(getwd()) != 'docs') setwd('docs')

grd = '../data/GOMFK_I90VAR3_SM1k.grd'
b = brick(grd)

pfx = c('CLASS.OCI','CLASS.sw','P.OCI','P.sw')
sfx = c('0304','0311','0502','0509','0912','0919')

map_i = function(i){
  vars = sprintf('%s_%s', pfx[i], sfx)
  vals = sapply(vars, function(x) getValues(raster(b, layer=x)))
  pal = colorNumeric('Spectral', vals, na.color = "transparent")
  
  leaflet() %>%
    addProviderTiles('Esri.OceanBasemap') %>%
    addRasterImage(raster(b, layer=sprintf('%s_%s',pfx[i],sfx[1])), colors = pal, opacity=0.7, group=sfx[1]) %>%
    addRasterImage(raster(b, layer=sprintf('%s_%s',pfx[i],sfx[2])), colors = pal, opacity=0.7, group=sfx[2]) %>%
    addRasterImage(raster(b, layer=sprintf('%s_%s',pfx[i],sfx[3])), colors = pal, opacity=0.7, group=sfx[3]) %>%
    addRasterImage(raster(b, layer=sprintf('%s_%s',pfx[i],sfx[4])), colors = pal, opacity=0.7, group=sfx[4]) %>%
    addRasterImage(raster(b, layer=sprintf('%s_%s',pfx[i],sfx[5])), colors = pal, opacity=0.7, group=sfx[5]) %>%
    addRasterImage(raster(b, layer=sprintf('%s_%s',pfx[i],sfx[6])), colors = pal, opacity=0.7, group=sfx[6]) %>%
    addLegend('topleft', pal = pal, values = vals, title = pfx[i], opacity = 1) %>%
    addLayersControl(overlayGroups = sfx, options = layersControlOptions(collapsed = FALSE))
}
map_i(1)
map_i(2)
map_i(3)
map_i(4)
#[CLASS|P].[OCI|sw]
```

## App

- selectinput choose class

```{r}
mat = file.path(dir_mat, mats$mat[1])
m = readMat(mat)
names(m)
y = m$lat1
dim(y)
range(diff(y[,1]))
plot(y[,1])
x = m$lon1
plot(x[1,])
range(x[1,])
range(diff(x[1,]))
diff(x[1,])[1:3]
diff(x[1,])[(nrow(x)-3):nrow(x)]
dim(x)
z = m$CLASS
dim(z)
```

