---
title: "CMARS EBSA"
output: html_document
---

Rationale:
- select ROI, eg CMARS EBSA
- get obis
- get EEZ w/in ROI, join obis id
  - TODO: in/out MPA

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(sf)
library(mapview)
library(robis2) # devtools::install_github('iobis/robis2')
library(rmapshaper)
library(geojsonio)

if (basename(getwd()) != 'technical') setwd('technical')

cols_drop = c(
  'acceptedNameUsage','acceptedNameUsageID','accessRights','associatedMedia','associatedReferences','associatedSequences','associatedTaxa',
  'basisOfRecord','behavior','bibliographicCitation',
  'collectionID','continent','coordinatePrecision','coordinateUncertaintyInMeters','countryCode','county',
  'dataGeneralizations','datasetID','dateIdentified','division','dynamicProperties',
  'establishmentMeans','eventID','eventRemarks','eventTime',
  'fieldNotes','fieldNumber','footprintSRS','footprintWKT','forma',
  'geodeticDatum',
  'habitat','higherClassification','higherGeography','higherGeographyID',
  'identificationID','identificationQualifier','identificationReferences','identificationRemarks','identifiedBy','individualCount',
  'individualID','informationWithheld','infraclass','infrakingdom','infraorder','infraphylum','institutionID','island','islandGroup',
  'language','lifeStage','locality','locationAccordingTo','locationID','locationRemarks',
  'materialSampleID','maximumDepthInMeters','minimumDepthInMeters','modified','municipality',
  'nameAccordingTo','nameAccordingToID','namePublishedIn','namePublishedInID',
  'occurrenceID','occurrenceRemarks','occurrenceStatus','originalNameUsage','originalNameUsageID','otherCatalogNumbers','ownerInstitutionCode',
  'parvorder',
  'section',
  'recordNumber','recordedBy','references','reproductiveCondition','rights','rightsHolder',
  'scientificNameAuthorship','sex','source',
  'stateProvince','subclass','subdivision','subfamily','subforma','subgenus','subkingdom','suborder',
  'subphylum','subsection','subspecies','subterclass','subtribe','subvariety',
  'superclass','superfamily','superorder','supertribe',
  'taxonConceptID','taxonID','taxonRank','taxonRemarks','taxonomicStatus',
  'tribe','type','typeStatus',
  'variety','vernacularName',
  'waterBody')
```


```{r get cmars poly}
cmars_geo = 'https://chm.cbd.int/api/v2013/documents/FB73B0D1-64FB-367F-405A-51AAA4C060F7/attachments/ETTP_8_EBSA.geojson'
cmars_sf = read_sf(cmars_geo)
```

```{r get obis pts for cmars poly}
#occurrence(geometry = st_as_text(st_geometry(cmars)))
# Error: Request-URI Too Long
# nchar(st_as_text(st_geometry(cmars))) # 120,525

# generalize area for querying obis
wkt = cmars %>%
  st_buffer(dist=1) %>%
  geojson_json() %>%
  ms_simplify() %>%
  geojson_sp() %>%
  st_as_sf() %>%
  st_geometry() %>%
  st_as_text()
nchar(wkt)  # 21,662 # 727

# get obis data, drop cols
obis_tbl = occurrence(geometry=wkt) %>% 
  as_tibble() %>%
  select_(.dots = setdiff(names(obis), cols_drop)) # names(obis_tbl)

# turn obis into sf
obis_sf = st_sf(
  obis_tbl, 
  geometry = st_sfc(
    with(
      obis_tbl, 
      map2(decimalLongitude, decimalLatitude, function(x, y) st_point(c(x, y)))))) %>%
  st_set_crs(4326)

# rm obis outside original roi: 137,277 -> 64,342
obis_sf = obis_sf %>%
  slice(st_intersects(cmars_sf, obis_sf)[[1]])

mapview(obis_sf)
```

## Marine Regions

- EEZ
    - + Disputed Territory
    - + Joint regime (EEZ)
- Territorial Sea
- Marine Protected Area (MPA)
- IHO Sea Area
- FAO Subareas
- Marine Subregion
- Marine Ecoregion of the World (MEOW)

```{r eez mregions FAIL, eval=F}
library(mregions) # install.packages('mregions')

mr_place_types() %>% View() # 

eez_tbl =  mr_records_by_type(type='EEZ') %>% 
  bind_rows(
    mr_records_by_type(type='EEZ', offset=100),
    mr_records_by_type(type='EEZ', offset=200),
    mr_records_by_type(type='Disputed Territory'),
    mr_records_by_type(type='Joint regime (EEZ)')) %>%
  as_tibble() # View(eez_tbl)
#table(eez_tbl$placeType)
#Disputed Territory                EEZ Joint regime (EEZ) 
#                41                251                 20
#table(eez_sf$gazetteerSource)
eez_src = eez_tbl %>% 
  as_tibble() %>%
  group_by(gazetteerSource) %>%
  summarize(
    n = n()) %>%
  arrange(n) %>%
  tail(1) %>%
  .$gazetteerSource
eez_tbl = eez_tbl %>%
  filter(gazetteerSource == eez_src)
#table(eez_tbl$placeType)
#Disputed Territory                EEZ Joint regime (EEZ) 
#                25                237                 19
eez_tbl = eez_tbl %>%
  left_join(
    mr_names('MarineRegions:eez') %>%
      mutate(
        mrgid = as.integer(mrgid)),
    by=c('MRGID'='mrgid'))
#eez_tbl %>% View()

# eez_tbl = eez_tbl %>%
#   mutate(

# eez_tbl %>%
#   select(minLongitude, maxLongitude, minLatitude, maxLatitude) %>%
#   filter(is.na(minLongitude)) %>%
#   View()
#   summary()
#   filter(is.null())

eez_sf = st_sf(
  eez_tbl,
  geometry = st_sfc(
    with(
      eez_tbl, 
      pmap(list(
        xmin = minLongitude, 
        xmax = maxLongitude,
        ymin = minLatitude, 
        ymax = maxLatitude,
        x    = longitude, 
        y    = latitude),  
        function(xmin, xmax, ymin, ymax, x, y){
          #browser()
          if (all(
            !is.na(xmin),
            !is.na(xmax),
            !is.na(ymin),
            !is.na(ymax))){
            st_polygon(list(matrix(c(
              xmin, ymin,
              xmin, ymax,
              xmax, ymax,
              xmax, ymin,
              xmin, ymin), ncol=2, byrow=T)))
          } else {
            st_buffer(st_point(c(x, y)), dist=1)
          }
        })))) %>%
  st_set_crs(4326) # eez_sf
# plot(eez_sf['preferredGazetteerName'])

eez_i = eez_sf %>%
  slice(st_intersects(cmars_sf, eez_sf)[[1]]) #%>%
  eez_i %>% as_tibble() %>% View()
  mutate(
    key = '')

  st_set_geometry(NULL) %>% View()
  select()
names(eez_sf)
#shp <- mr_shp(key = "MarineRegions:eez_iho_union_v2", maxFeatures = 5)
shp = mr_shp(key='MarineRegions:eez', maxFeatures=2) # filter=eez_sf$preferredGazetteerName[[1]]) # MarineRegions:land_v9
shp = mr_shp(key='MarineRegions:eez', filter="American Samoa Exclusive Economic Zone") # filter=eez_sf$preferredGazetteerName[[1]]) # MarineRegions:land_v9 # MarineRegions:eez_24nm
shp@data$geoname
# &PROPERTYNAME=STATE_NAME&CQL_FILTER=STATE_NAME='Illinois'

mr_layers()


fid = eez_i$id[[1]] # fid='eez.3'
zip = sprintf('%s/%s.zip', rappdirs::user_cache_dir('mregions'), fid)
dir = sprintf('%s/%s'    , rappdirs::user_cache_dir('mregions'), fid)
f1 = mr_features_get(type='MarineRegions:eez', featureID=fid, format='SHAPE-ZIP', path=zip)# %>%
  #as.json() %>% geojson_sp() %>% st_as_sf()
unzip(zip, exdir=dir)
list.files(dir)
f_sf = read_sf(dir)

devtools::install_github('ropenscilabs/mregions')
shp <- mr_shp(name = "Belgian Exclusive Economic Zone")


f_j = read_sf('http://geo.vliz.be/geoserver/MarineRegions/wms?service=WFS&version=1.1.0&request=GetFeature&typeName=MarineRegions:eez&propertyname=mrgid&outputFormat=application/json&cql_filter=mrgid=3293')

f_j$bbox

plot(f_j)
mapview(f_sf)
mr_names2

library(leaflet)
leaflet() %>%
  addTiles() %>%
  addPolygons(data = shp)

View(eez_sf) %>% st_set_geometry(NULL) %>% select(-geometry) %>% View()
mr_geo_code()

mr_as_wkt

res3 <- mr_geojson(key = "Morocco:dam")
class(res3)

eez_rnames = mr_names('MarineRegions:eez') # layer = one of MarineRegions:eez, MarineRegions:eez_boundaries, MarineRegions:iho, MarineRegions:fao, or MarineRegions:lme
# View(eez_rnames)

mrgid

eez2 = eez_rnames %>%
  left_join(
    eez_tbl,
    by=c('geoname'='preferredGazetteerName')) # View(eez2) %>%
  filter()

names(eez_tbl)

# setup ~/mbon_data_big: cd ~; ln -s /mbon/data_big mbon_data_big
eez_shp         = '~/mbon_data_big/technical/boundaries/eez/eez.shp'
eez_s005_shp    = '~/mbon_data_big/technical/boundaries/eez_derived/eez_s005.shp'
esp_s005_shp    = '~/mbon_data_big/technical/boundaries/eez_derived/esp_s005.shp'
```

```{r eez wfs}
# eez_shp = '/Volumes/Best HD/mbon_data_big/technical/boundaries/eez/eez.shp'
# eez_s005_shp = '/Volumes/Best HD/mbon_data_big/technical/boundaries/eez_derived/eez_s005.shp'
# eez_sf = read_sf(eez_shp) #%>%
eez_rdata = 'data/eez.rdata'

if (!file.exists(eez_rdata)){
  eez_all_sf = read_sf('http://geo.vliz.be/geoserver/MarineRegions/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=MarineRegions:eez&maxFeatures=300') # 2.2 min
  saveRDS(eez_all_sf, file=eez_rdata)
}
eez_all_sf = readRDS(eez_rdata)
```


```{r eez in roi}
bbox_ply = function(bb){
  # bb = st_bbox(cmars_sf)
  st_sfc(st_polygon(list(matrix(c(
    bb[['xmin']], bb[['ymin']],
    bb[['xmin']], bb[['ymax']],
    bb[['xmax']], bb[['ymax']],
    bb[['xmax']], bb[['ymin']],
    bb[['xmin']], bb[['ymin']]), ncol=2, byrow=T)))) %>%
    st_set_crs(attr(bb,'crs'))
}

# filter by eez's within bounding box of cmars
eez_sf = eez_all_sf %>%
  slice(st_intersects(st_bbox(cmars_sf) %>% bbox_ply(), eez_all_sf)[[1]])
```

```{r obis by eez}
# obis_sf = obis_sf %>% select(-eez_mrgid) # names(obis_sf)
system.time({
obis_sf = st_join(obis_sf, eez_sf %>% select(eez_mrgid = mrgid))
}) # obis nrows=136K, eez hires intersects: 1.4 min

table(obis_sf$eez_mrgid)

names(obis_sf)
mapview(obis_sf, zcol='eez_mrgid')
```


