---
title: "obis"
output:
  html_document:
    toc: true
    toc_float: true
    code_folding: hide
---

## Data Sources

Going to use [robis](https://github.com/iobis/robis), R client for the OBIS API, to fetch.

See also: [fetch OBIS data globally · Issue #19 · marinebon/sdg14](https://github.com/marinebon/sdg14/issues/19)


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

dir_obis       = '~/mbon_data_big/technical/obis'
dir_obis_cache = file.path(dir_obis, 'cache')
if (!dir.exists(dir_obis_cache)) dir.create(dir_obis_cache, recursive=T, showWarnings=F)
  
# setup ~/mbon_data_big: cd ~; ln -s /mbon/data_big mbon_data_big
occ_csv = file.path(dir_obis, 'occurrences.csv')
```


## Global all at once

```{r single obis fetch}
library(tidyverse)
library(robis) # devtools::install_github('iobis/robis')

# setup geom
geom = sprintf(
  'POLYGON ((%d %d, %d %d, %d %d, %d %d, %d %d))',
  -180, -90, -180, 90, 180, 90, 180, -90, -180, -90)

# fetch records
system.time({
  occ = occurrence(geometry = geom) # Retrieved 6458000 records of 47777791 (13%) May 1, 5:02pm
})

# save to rds
system.time({
  saveRDS(occ, file.path(dir_obis, 'obis_occ.rds'))
})
```


## Global by 1 deg cells

```{r fetch obis by 1deg cells}
library(tidyverse)
library(robis) # devtools::install_github('iobis/robis')
library(data.table)

# get all occurrences globally, iterating by 1 deg cells
for (x in seq(-180, 179)){ # x = seq(-180, 180)[1] # x = 0
  for (y in seq(-90, 89)){ # y = seq(-90, 90)[1] # y = 0
    
    # setup geom and csv
    geom = sprintf(
      'POLYGON ((%d %d, %d %d, %d %d, %d %d, %d %d))',
      x, y, x, y+1, x+1, y+1, x+1, y, x, y)
    occ_xy_csv = sprintf('%s/occ_%03d_%03d.csv', dir_obis_cache, x, y)
    
    if (!file.exists(occ_xy_csv)){
      # fetch records
      cat(sprintf('Fetching %03d, %03d\n', x, y))
      occ_xy = occurrence(geometry = geom)
    
      # write to csv
      write_csv(occ_xy, occ_xy_csv)
    }
  }
}

# summarize longitudinally
for (y in seq(-90, 89)){ # y = seq(-90, 90)[1] # y = 50
  cat(sprintf('%d\n', y))
  
  rds = sprintf('%s/occ_%03d.rds', dir_obis_cache, y)
  if (file.exists(rds)){
    cat(sprintf('  skipping: %s exists\n', basename(rds)))
    next
  }

  csvs = tibble(
    path = list.files(
      dir_obis_cache, full.names=T,
      pattern = sprintf('occ_[-]*[0-9]+_%03d\\.csv', y))) %>%
    mutate(
      file = basename(path),
      size = file.size(path)) %>%
    filter(size > 0)
  
  if (nrow(csvs) == 0){
    cat('  no data\n')
    next
  }
  
  suppressMessages({
    df_list = lapply(csvs$path, read_csv)
  })
  #  row     col   expected        actual
  #1013 eventID an integer NIWA Database
  #1102 modified date like  May 10 2010 11:36AM
  #2610 dateIdentified date like  1985-01-18T18:00:00
  #1055 occurrenceID no trailing characters   _530
  #...
  
  df = rbindlist(df_list, fill=T)
  
  saveRDS(df, rds)
}

# tbl of longitudinal files
rdss = tibble(
  path = list.files(
    dir_obis_cache, full.names=T,
    pattern = sprintf('occ_[-]*[0-9]+\\.rds'))) %>% 
  mutate(
    file = basename(path),
    size = file.size(path)) %>% 
  filter(size > 0) %>%
  arrange(desc(size)) %>%
  mutate(
    size_sum = sum(size),
    size_cum = cumsum(size),
    size_pct = size_cum / size_sum * 100)

for (i in 1:nrow(rdss)){ # i=1

  cat(sprintf('%02d: %s (%0.2f%%)\n', i, basename(rdss$path[i]), rdss$size_pct[i]))
  d = readRDS(rdss$path[i])
  
  if (!'yearcollected' %in% names(d)){
    cat('  SKIPPING b/c missing: yearcollected\n')
    next
  }
  
  d = d %>%
    select(
      id,decimalLongitude,decimalLatitude,yearcollected,
      institutionCode,datasetName,
      phylum,class,order,family,genus,species,scientificName,
      aphiaID,obisID,resourceID) %>%
    mutate(
      year = as.integer(yearcollected)) %>%
    select(-yearcollected) %>%
    filter(!is.na(year)) %>%
    as_tibble()

  if (i == 1){
    D = d
  } else {
    D = bind_rows(D, d)
  }
}

#write_csv(D, file.path(dir_obis, 'obis_occ.csv'))
saveRDS(D, file.path(dir_obis, 'obis_occ.rds'))                     # 532 MB; 43,140,428 rows of obs
readr::write_csv(occ, '~/mbon_data_big/technical/obis/occ_rds.csv') # 9.15 GB

system.time({
  occ = readRDS('~/mbon_data_big/technical/obis/obis_occ.rds')      # 23 secs
})
```

