---
title: "test-postgis"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

[marinebon/sdg14 #2: load data for infographic: NCEAS ecosystems, OBIS observations, MarineRegions EEZ, ddgrid hexagons](https://github.com/marinebon/sdg14/issues/2)

[Loading Point Data from a CSV File in PostGIS](https://spatialdbadvisor.com/postgis_tips_tricks/118/loading-point-data-from-a-csv-file-in-postgis)

- load obis csv into pg

- load eez into pg

## load obis_occ.csv into postgis db

On `ben@mbon`, connect to database docker container `postgis`:

```
docker exec -it postgis bash
```

Once in `postgis` container, connect to:

```bash
psql -h localhost -U docker -p 5432 -d postgres
```

Once in `postgres=#` prompt paste sql generated by...

### generate SQL

```{r create sql}
library(tidyverse)

d = read_csv('~/mbon_data_big/technical/obis/obis_occ_head10k.csv')

col_names = names(d)
col_types = sapply(names(d), function(x) class(d[[x]]))

pg_types = c('integer'='int', 'numeric'='float', 'character'='varchar')

# create table
cat(paste(c(
  'CREATE TABLE obis_occ (',
  paste(sprintf('  "%s" %s', col_names, pg_types[col_types]), collapse=',\n'),
  ');'),
  collapse='\n'))

# copy from csv
cat(paste0(c(
  "COPY obis_occ ( ",
  paste0(c(sprintf('"%s"', col_names, pg_types[col_types])), collapse=',\n    '),
  " )",
  "FROM '/mbon/data_big/technical/obis/obis_occ.csv'",
  "WITH DELIMITER AS ',' CSV HEADER ;"),
  collapse='\n'))

```

```sql

CREATE DATABASE mbon;
\connect mbon;
-- Enable PostGIS (includes raster)
CREATE EXTENSION postgis;
-- Enable Topology
CREATE EXTENSION postgis_topology;

DROP TABLE IF EXISTS obis_occ CASCADE;
CREATE TABLE obis_occ (
  "id" int,
  "decimalLongitude" float,
  "decimalLatitude" float,
  "institutionCode" varchar,
  "datasetName" varchar,
  "phylum" varchar,
  "class" varchar,
  "order" varchar,
  "family" varchar,
  "genus" varchar,
  "species" varchar,
  "scientificName" varchar,
  "aphiaID" int,
  "obisID" int,
  "resourceID" int,
  "year" int );

-- copy from csv
\copy obis_occ FROM '/mbon/data_big/technical/obis/obis_occ_head10k.csv' WITH DELIMITER ',' CSV HEADER;
-- \copy obis_occ FROM '/mbon/data_big/technical/obis/obis_occ.csv' WITH DELIMITER ',' CSV HEADER NULL AS 'NA';

-- add primary key
ALTER TABLE obis_occ ADD COLUMN gid serial PRIMARY KEY;

-- Add point geometry column to table
ALTER TABLE obis_occ ADD COLUMN geom geometry(Point,4326);

-- Populate column with point geometries
update obis_occ set geom = ST_SetSRID(ST_MakePoint( "decimalLongitude", "decimalLatitude" ), 4326);

-- Create a spatial index on points
CREATE INDEX idx_obis_occ_geom ON obis_occ USING GIST(geom);
```


## test PG connection methods

### RPostgreSQL

```{r RPostgreSQL}
library(tidyverse)
library(RPostgreSQL)

db = list(
  host = read_delim('/etc/hosts', '\t', col_names=c('ip','host')) %>%
    separate(host, c('name','image'), extra='merge', fill='left') %>%
    filter(name=='postgis') %>%
    .$ip,
  port = 5432,
  user = 'docker',
  pass = readLines('/mbon/.pg_pass_docker'),
  name = 'mbon')
db$dsn=sprintf(
  "PG:dbname=%s host=%s port=%s user=%s password=%s", 
  db$name, db$host, db$port, db$user, db$pass)

con = dbConnect(
  dbDriver('PostgreSQL'), 
  dbname=db$name, 
  user=db$user, password=db$pass, host=db$host, port=db$port)

dbListTables(con)
dbExistsTable(con, "obis_occ")
```

### rgdal

```{r rgdal}
library(rgdal)

# list tables in db
ogrListLayers(db$dsn)

# fetch polygon
occ = readOGR(dsn=dsn,"obis_occ")

plot(occ)
```

### sf

```{r sf}
library(sf)

st_layers(dsn)
occ = st_read(dsn, 'obis_occ')

plot(occ['id'])


occ3 = st_read_db(con, query='SELECT * FROM obis_occ LIMIT 3')
```


